#!/bin/sh

# first find which PHP binary to use
if test "x$PHP_PEAR_PHP_BIN" != "x"; then
  PHP="$PHP_PEAR_PHP_BIN"
else
  if test "/opt/lampp/bin/php" = '@'php_bin'@'; then
    PHP=php 
  else
    PHP="/opt/lampp/bin/php"
  fi
fi

# then look for the right pear include dir
if test "x$PHP_PEAR_INSTALL_DIR" != "x"; then
  INCDIR=$PHP_PEAR_INSTALL_DIR
  INCARG="-d include_path=$PHP_PEAR_INSTALL_DIR"
else
  if test "/home/bkrein/public_html/landoc/trunk/include/pear/php" = '@'php_dir'@'; then
    INCDIR=`dirname $0`
    INCARG=""  
  else
    INCDIR="/home/bkrein/public_html/landoc/trunk/include/pear/php"
    INCARG="-d include_path=/home/bkrein/public_html/landoc/trunk/include/pear/php"
  fi
fi

exec $PHP -C -n -q $INCARG -d output_buffering=1 -d safe_mode=0 $INCDIR/peclcmd.php "$@"
